//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSoftConsult.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class emp_dbEntities : DbContext
    {
        public emp_dbEntities()
            : base("name=emp_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblEmpDesig> tblEmpDesigs { get; set; }
        public virtual DbSet<tblEmpDptLev> tblEmpDptLevs { get; set; }
        public virtual DbSet<tblEmpEmployee> tblEmpEmployees { get; set; }
        public virtual DbSet<tblEmpGender> tblEmpGenders { get; set; }
        public virtual DbSet<tblEmpGrade> tblEmpGrades { get; set; }
        public virtual DbSet<tblEmpJobStatu> tblEmpJobStatus { get; set; }
        public virtual DbSet<tblEmpLeave> tblEmpLeaves { get; set; }
        public virtual DbSet<tblEmpLoc> tblEmpLocs { get; set; }
        public virtual DbSet<tblEmpNation> tblEmpNations { get; set; }
        public virtual DbSet<tblEmpReligion> tblEmpReligions { get; set; }
        public virtual DbSet<tblEmpSec> tblEmpSecs { get; set; }
        public virtual DbSet<tblEmpStatu> tblEmpStatus { get; set; }
        public virtual DbSet<tblEmpSur> tblEmpSurs { get; set; }
    
        public virtual ObjectResult<stpEmp_Employee_Result> stpEmp_Employee(Nullable<decimal> nS_NO, string sS_ID, string sS_Name, string sS_FName, string sS_IdNo, Nullable<System.DateTime> dS_DOB, Nullable<System.DateTime> dS_IdExpire, string sS_Desig, string sS_Depart, Nullable<System.DateTime> sS_Join, string sS_Reason, Nullable<System.DateTime> dS_CD, Nullable<System.DateTime> dS_DL, Nullable<decimal> nEmp_DesigID, Nullable<decimal> nEmp_DptID, Nullable<decimal> nEmp_StatusID, Nullable<decimal> nEmp_LocID, Nullable<decimal> nEmp_SurID, Nullable<decimal> nEmp_GenderID, Nullable<decimal> nEmp_GradeID, Nullable<decimal> nEmp_JobStatusID, Nullable<decimal> nEmp_LeaveID, Nullable<decimal> nEmp_NationID, Nullable<decimal> nEmp_ReligionID, Nullable<decimal> nEmp_SecID, Nullable<decimal> nIsUpdate, Nullable<decimal> pageNumber, Nullable<decimal> pageSize)
        {
            var nS_NOParameter = nS_NO.HasValue ?
                new ObjectParameter("nS_NO", nS_NO) :
                new ObjectParameter("nS_NO", typeof(decimal));
    
            var sS_IDParameter = sS_ID != null ?
                new ObjectParameter("sS_ID", sS_ID) :
                new ObjectParameter("sS_ID", typeof(string));
    
            var sS_NameParameter = sS_Name != null ?
                new ObjectParameter("sS_Name", sS_Name) :
                new ObjectParameter("sS_Name", typeof(string));
    
            var sS_FNameParameter = sS_FName != null ?
                new ObjectParameter("sS_FName", sS_FName) :
                new ObjectParameter("sS_FName", typeof(string));
    
            var sS_IdNoParameter = sS_IdNo != null ?
                new ObjectParameter("sS_IdNo", sS_IdNo) :
                new ObjectParameter("sS_IdNo", typeof(string));
    
            var dS_DOBParameter = dS_DOB.HasValue ?
                new ObjectParameter("dS_DOB", dS_DOB) :
                new ObjectParameter("dS_DOB", typeof(System.DateTime));
    
            var dS_IdExpireParameter = dS_IdExpire.HasValue ?
                new ObjectParameter("dS_IdExpire", dS_IdExpire) :
                new ObjectParameter("dS_IdExpire", typeof(System.DateTime));
    
            var sS_DesigParameter = sS_Desig != null ?
                new ObjectParameter("sS_Desig", sS_Desig) :
                new ObjectParameter("sS_Desig", typeof(string));
    
            var sS_DepartParameter = sS_Depart != null ?
                new ObjectParameter("sS_Depart", sS_Depart) :
                new ObjectParameter("sS_Depart", typeof(string));
    
            var sS_JoinParameter = sS_Join.HasValue ?
                new ObjectParameter("sS_Join", sS_Join) :
                new ObjectParameter("sS_Join", typeof(System.DateTime));
    
            var sS_ReasonParameter = sS_Reason != null ?
                new ObjectParameter("sS_Reason", sS_Reason) :
                new ObjectParameter("sS_Reason", typeof(string));
    
            var dS_CDParameter = dS_CD.HasValue ?
                new ObjectParameter("dS_CD", dS_CD) :
                new ObjectParameter("dS_CD", typeof(System.DateTime));
    
            var dS_DLParameter = dS_DL.HasValue ?
                new ObjectParameter("dS_DL", dS_DL) :
                new ObjectParameter("dS_DL", typeof(System.DateTime));
    
            var nEmp_DesigIDParameter = nEmp_DesigID.HasValue ?
                new ObjectParameter("nEmp_DesigID", nEmp_DesigID) :
                new ObjectParameter("nEmp_DesigID", typeof(decimal));
    
            var nEmp_DptIDParameter = nEmp_DptID.HasValue ?
                new ObjectParameter("nEmp_DptID", nEmp_DptID) :
                new ObjectParameter("nEmp_DptID", typeof(decimal));
    
            var nEmp_StatusIDParameter = nEmp_StatusID.HasValue ?
                new ObjectParameter("nEmp_StatusID", nEmp_StatusID) :
                new ObjectParameter("nEmp_StatusID", typeof(decimal));
    
            var nEmp_LocIDParameter = nEmp_LocID.HasValue ?
                new ObjectParameter("nEmp_LocID", nEmp_LocID) :
                new ObjectParameter("nEmp_LocID", typeof(decimal));
    
            var nEmp_SurIDParameter = nEmp_SurID.HasValue ?
                new ObjectParameter("nEmp_SurID", nEmp_SurID) :
                new ObjectParameter("nEmp_SurID", typeof(decimal));
    
            var nEmp_GenderIDParameter = nEmp_GenderID.HasValue ?
                new ObjectParameter("nEmp_GenderID", nEmp_GenderID) :
                new ObjectParameter("nEmp_GenderID", typeof(decimal));
    
            var nEmp_GradeIDParameter = nEmp_GradeID.HasValue ?
                new ObjectParameter("nEmp_GradeID", nEmp_GradeID) :
                new ObjectParameter("nEmp_GradeID", typeof(decimal));
    
            var nEmp_JobStatusIDParameter = nEmp_JobStatusID.HasValue ?
                new ObjectParameter("nEmp_JobStatusID", nEmp_JobStatusID) :
                new ObjectParameter("nEmp_JobStatusID", typeof(decimal));
    
            var nEmp_LeaveIDParameter = nEmp_LeaveID.HasValue ?
                new ObjectParameter("nEmp_LeaveID", nEmp_LeaveID) :
                new ObjectParameter("nEmp_LeaveID", typeof(decimal));
    
            var nEmp_NationIDParameter = nEmp_NationID.HasValue ?
                new ObjectParameter("nEmp_NationID", nEmp_NationID) :
                new ObjectParameter("nEmp_NationID", typeof(decimal));
    
            var nEmp_ReligionIDParameter = nEmp_ReligionID.HasValue ?
                new ObjectParameter("nEmp_ReligionID", nEmp_ReligionID) :
                new ObjectParameter("nEmp_ReligionID", typeof(decimal));
    
            var nEmp_SecIDParameter = nEmp_SecID.HasValue ?
                new ObjectParameter("nEmp_SecID", nEmp_SecID) :
                new ObjectParameter("nEmp_SecID", typeof(decimal));
    
            var nIsUpdateParameter = nIsUpdate.HasValue ?
                new ObjectParameter("nIsUpdate", nIsUpdate) :
                new ObjectParameter("nIsUpdate", typeof(decimal));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(decimal));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stpEmp_Employee_Result>("stpEmp_Employee", nS_NOParameter, sS_IDParameter, sS_NameParameter, sS_FNameParameter, sS_IdNoParameter, dS_DOBParameter, dS_IdExpireParameter, sS_DesigParameter, sS_DepartParameter, sS_JoinParameter, sS_ReasonParameter, dS_CDParameter, dS_DLParameter, nEmp_DesigIDParameter, nEmp_DptIDParameter, nEmp_StatusIDParameter, nEmp_LocIDParameter, nEmp_SurIDParameter, nEmp_GenderIDParameter, nEmp_GradeIDParameter, nEmp_JobStatusIDParameter, nEmp_LeaveIDParameter, nEmp_NationIDParameter, nEmp_ReligionIDParameter, nEmp_SecIDParameter, nIsUpdateParameter, pageNumberParameter, pageSizeParameter);
        }
    }
}
