//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSoftConsult.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpEmployee
    {
        public decimal E_SNO { get; set; }
        public string E_SID { get; set; }
        public string E_Name { get; set; }
        public string E_FName { get; set; }
        public string E_IdNo { get; set; }
        public Nullable<System.DateTime> E_DOB { get; set; }
        public Nullable<System.DateTime> E_IDExpire { get; set; }
        public string E_Desig { get; set; }
        public string E_Depart { get; set; }
        public Nullable<System.DateTime> E_Join { get; set; }
        public string E_Reason { get; set; }
        public Nullable<System.DateTime> E_CD { get; set; }
        public Nullable<System.DateTime> E_DL { get; set; }
        public decimal Emp_DesigID { get; set; }
        public decimal Emp_DptID { get; set; }
        public decimal Emp_StatusID { get; set; }
        public decimal Emp_LocID { get; set; }
        public decimal Emp_SurID { get; set; }
        public decimal Emp_GenderID { get; set; }
        public decimal Emp_GradeID { get; set; }
        public decimal Emp_JobStatusID { get; set; }
        public decimal Emp_LeaveID { get; set; }
        public decimal Emp_NationID { get; set; }
        public decimal Emp_ReligionID { get; set; }
        public decimal Emp_SecID { get; set; }
    
        public virtual tblEmpDesig tblEmpDesig { get; set; }
        public virtual tblEmpDptLev tblEmpDptLev { get; set; }
        public virtual tblEmpGender tblEmpGender { get; set; }
        public virtual tblEmpGrade tblEmpGrade { get; set; }
        public virtual tblEmpJobStatu tblEmpJobStatu { get; set; }
        public virtual tblEmpLeave tblEmpLeave { get; set; }
        public virtual tblEmpLoc tblEmpLoc { get; set; }
        public virtual tblEmpNation tblEmpNation { get; set; }
        public virtual tblEmpReligion tblEmpReligion { get; set; }
        public virtual tblEmpSec tblEmpSec { get; set; }
        public virtual tblEmpStatu tblEmpStatu { get; set; }
        public virtual tblEmpSur tblEmpSur { get; set; }
    }
}
