//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSoftConsult.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpLeave
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmpLeave()
        {
            this.tblEmpEmployees = new HashSet<tblEmpEmployee>();
        }
    
        public decimal Leave_ID { get; set; }
        public Nullable<int> Leave_COD { get; set; }
        public string Leave_DESC { get; set; }
        public Nullable<bool> Leave_IsActive { get; set; }
        public Nullable<System.DateTime> Leave_CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmpEmployee> tblEmpEmployees { get; set; }
    }
}
