//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSoftConsult.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpDesig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmpDesig()
        {
            this.tblEmpEmployees = new HashSet<tblEmpEmployee>();
        }
    
        public decimal Desig_ID { get; set; }
        public string Desig_Name { get; set; }
        public Nullable<bool> Desig_IsActive { get; set; }
        public Nullable<System.DateTime> Desig_CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmpEmployee> tblEmpEmployees { get; set; }
    }
}
