//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSoftConsult.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpDptLev
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmpDptLev()
        {
            this.tblEmpEmployees = new HashSet<tblEmpEmployee>();
        }
    
        public decimal DptLev_ID { get; set; }
        public string DptLev_Code { get; set; }
        public string DptLev_Desc { get; set; }
        public Nullable<bool> DptIsActive { get; set; }
        public Nullable<System.DateTime> DptCreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmpEmployee> tblEmpEmployees { get; set; }
    }
}
